title: Hello, I'm Ben Prescott!
description: > # this means to ignore newlines until "baseurl:"
  Exploring the Boundaries of Innovation.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bcprescott.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ben Prescott # add your name
author-img: benblog.jpg # add your photo
about-author: I am a data scientist with a passion for solving unique challenges with math and code.  # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: bcprescott # add your Github handle
social-linkedin: benjaminprescott
social-email: bcprescott@outlook.com

# Disqus
# discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
